apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: ace-hello-world-is
  namespace: ace-hello-world
spec:
  enableMetrics: true
  license:
    accept: true
    license: L-APEH-CJUCNR
    use: CloudPakForIntegrationNonProductionFREE
  pod:
    containers:
      runtime:
        image: image-registry.openshift-image-registry.svc:5000/ace-hello-world/ace-hello-world:a6f27d20eee62a64bd810d005550c95d37cc00db
        resources:
          limits:
            cpu: 300m
            memory: 368Mi
          requests:
            cpu: 300m
            memory: 368Mi
  adminServerSecure: true
  router:
    timeout: 120s
  designerFlowsOperationMode: disabled
  createDashboardUsers: true
  service:
    endpointType: https
  version: 12.0.7.0-r2
  replicas: 1