apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: ace-hello-world-is
  namespace: ace-hello-world
spec:
  enableMetrics: true
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9483'
  license:
    accept: true
    license: L-APEH-CJUCNR
    use: CloudPakForIntegrationNonProductionFREE
  pod:
    containers:
      runtime:
        resources:
          limits:
            cpu: 300m
            memory: 368Mi
          requests:
            cpu: 300m
            memory: 368Mi
  adminServerSecure: true
  forceFlowHTTPS:
    enabled: true
    secretName: ace-certificate-secret
  router:
    timeout: 120s
  designerFlowsOperationMode: disabled
  createDashboardUsers: true
  version: "12.0"
  barURL: >-
    http://example.com
  replicas: 1
