apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ace-certificate
spec:
  secretName: ace-certificate-secret
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
      - ace-hello-world
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - key encipherment
    - digital signature
    - server auth
    - client auth
  dnsNames:
    - '*.ace-hello-world.svc'
    - '*.ace-hello-world.local'
    - '*.ace-hello-world.svc.local.cluster'
  issuerRef:
    name: ace-selfsigned-issuer
