apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-ace-gradle
spec:
  results:
    - name: published-version
      description: The version of the application that was published to the artifact repository
  params:
    - description: Name of secret containing username and token for the repository to publish bar-files to
      name: ARTIFACT_REPO_SECRET_NAME
      type: string
    - default: 7.5.1
      name: GRADLE_VERSION
      type: string
    - default: ''
      name: GRADLE_TASK
      type: string
    - default: cp.icr.io/cp/appc/ace-server-prod@sha256:c41154c17a30bbbb6e1e4593c965f49ef3c86260e71143b8f33a6fbca277a3b9
      name: ACE_IMAGE
      type: string
      description: 'App Connect image from here: https://www.ibm.com/docs/en/app-connect/containers_cd?topic=obtaining-app-connect-enterprise-server-image-from-cloud-container-registry. Defaults to 12.0.8.0-r1'
  steps:
    - env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: $(params.ARTIFACT_REPO_SECRET_NAME)
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: $(params.ARTIFACT_REPO_SECRET_NAME)
      image: $(params.ACE_IMAGE)
      name: build
      resources: {}
      script: |
        #!/usr/bin/env bash
        export GRADLE_HOME=/home/aceuser/gradle/gradle-$(params.GRADLE_VERSION)
        export GRADLE_USER_HOME=/home/aceuser/gradle
        export PATH=$PATH:$GRADLE_HOME/bin
        export GRADLE_ZIP=gradle-$(params.GRADLE_VERSION)-bin.zip
        mkdir -p $GRADLE_USER_HOME
        if [ ! -d $GRADLE_HOME ]; then
          cd $GRADLE_USER_HOME
          curl -L https://services.gradle.org/distributions/${GRADLE_ZIP} -o ${GRADLE_ZIP}
          unzip ${GRADLE_ZIP}
          rm ${GRADLE_ZIP}
        fi
        cp /opt/ibm/ace-12/common/jdk/jre/lib/security/cacerts $GRADLE_USER_HOME
        if [ -f /workspace/extra-ca/ca.crt ]; then
          echo "Importing extra CA"
          openssl x509 -in /workspace/extra-ca/ca.crt -inform pem -out /tmp/ca.der -outform der
          # keytool -v -printcert -file /tmp/ca.der
          keytool -importcert -noprompt -alias extra-ca -keystore $GRADLE_USER_HOME/cacerts -storepass changeit -file /tmp/ca.der
          keytool -keystore $GRADLE_USER_HOME/cacerts -storepass changeit -list | grep extra-ca
          rm /tmp/ca.der
        fi
        gradle --info --no-daemon -Djavax.net.ssl.trustStore=$GRADLE_USER_HOME/cacerts -Djavax.net.ssl.trustStorePassword=changeit -g $GRADLE_USER_HOME/.gradle -p /workspace/source/application-code $(params.GRADLE_TASK)
        
        success=$?

        if [$success -ne 0]; then
          exit 1;
        fi
        gradle -q version | sed 's/[^ ]* //' | tee $(results.published-version.path)

      workingDir: /workspace/source/application-code    
  workspaces:
    - mountPath: /workspace/source
      name: source
    - mountPath: /home/aceuser/gradle
      name: cache
      optional: true
    - mountPath: /workspace/extra-ca
      name: extra-ca
      optional: true
