apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-ace-gradle-pipeline
spec:
  params:
    - name: gitrepo-application-code
      type: string
      default: https://github.com/Nordic-MVP-GitOps-Repos/ace-hello-world.git
    - description: name of secret with username and token to use for publishing bar file
      name: artifactreposecretname
      type: string
  tasks:
    - name: build-barfile-test-and-publish
      params:
        - name: ARTIFACT_REPO_SECRET_NAME
          value: $(params.artifactreposecretname)
        - name: GRADLE_TASK
          value: 'packageApplication buildWithUnitTests runUnitTests publish'
      runAfter:
        - git-clone-application-code
      taskRef:
        kind: Task
        name: build-ace-gradle
      workspaces:
        - name: source
          workspace: source
        - name: cache
          workspace: gradle-cache
        - name: extra-ca
          workspace: extra-ca
    - name: git-clone-application-code
      params:
        - name: url
          value: $(params.gitrepo-application-code)
        - name: revision
          value: ''
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: 'application-code'
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:e29585c67da42f3800f250c9c60159453af6ee7b4fff5669e27e17f34136a1d3
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
        - name: basic-auth
          workspace: git-credentials
  workspaces:
    - name: source
    - name: git-credentials
      optional: true
    - name: extra-ca
      optional: true
    - name: gradle-cache
      optional: true
