apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-ace-hello-world
  namespace: ace-hello-world
spec:
  tasks:
    - name: git-clone-ace-application
      params:
        - name: url
          value: 'https://github.com/Nordic-MVP-GitOps-Repos/ace-hello-world'
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: deleteExisting
          value: 'true'
        - name: subdirectory
          value: application-code
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:a538c423e7a11aae6ae582a411fdb090936458075f99af4ce5add038bb6983e8
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone-1-8-0
      workspaces:
        - name: output
          workspace: ace-tekton-workspace
    - name: s2i-ace-build-ace-image
      params:
        - name: PATH_CONTEXT
          value: application-code
        - name: TLSVERIFY
          value: 'true'
        - name: LICENSE
          value: accept
        - name: commit_id
          value: NA
        - name: commit_message
          value: NA
        - name: commit_user
          value: NA
        - name: BUILD_IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/ace-hello-world/s2i-ace:12.0.7.0-r2
        - name: IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/ace-hello-world/ace-hello-world:$(tasks.git-clone-ace-application.results.commit)
      runAfter:
        - git-clone-ace-application
        - git-clone-gitops-config
      taskRef:
        kind: Task
        name: s2i-ace
      workspaces:
        - name: source
          workspace: ace-tekton-workspace
    - name: git-clone-gitops-config
      params:
        - name: url
          value: 'https://github.com/Nordic-MVP-GitOps-Repos/ace-hello-world-gitops'
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: gitops-config
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:a538c423e7a11aae6ae582a411fdb090936458075f99af4ce5add038bb6983e8
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone-1-8-0
      workspaces:
        - name: output
          workspace: ace-tekton-workspace
    - name: yq-update-image-in-deployment
      runAfter:
        - s2i-ace-build-ace-image
      taskRef:
        kind: Task
        name: yq
      params:
        - name: SCRIPT
          value: |
            
            ls -lth gitops-config/components/app/base/ace-helloworld-integrationserver.yaml
            
            yq -i '.spec.pod.containers.runtime.image. = "image-registry.openshift-image-registry.svc:5000/ace-hello-world/ace-hello-world:$(tasks.git-clone-ace-application.results.commit)"' gitops-config/components/app/base/ace-helloworld-integrationserver.yaml
            
            cat gitops-config/components/app/base/deployment.yaml
        - name: image
          value: >-
            docker.io/mikefarah/yq:4.27.5@sha256:2be3626ed633fbe1fc33ee9343a1256a6be53334412b2251b9a859f8c145bb53
        - name: files
          value: []
      workspaces:
        - name: source
          workspace: ace-tekton-workspace
    - name: git-cli-commit-deployment-yaml
      runAfter: 
        - yq-update-image-in-deployment
      taskRef:
        kind: ClusterTask
        name: git-cli
      params:
        - name: BASE_IMAGE
          value: >-
            docker.io/alpine/git:v2.26.2@sha256:23618034b0be9205d9cc0846eb711b12ba4c9b468efdd8a59aac1d7b1a23363f
        - name: GIT_USER_NAME
          value: kjellmlarsson
        - name: GIT_USER_EMAIL
          value: kjell.m.larsson@se.ibm.com
        - name: GIT_SCRIPT
          value: |

            set -x

            cd gitops-config

            git status

            if [[ $(git status -uno --porcelain | wc -l) -eq 0 ]];  then 
                exit 0
            fi
            
            git add -u .
            git commit -m "Updated deployment of ace-hello-world app based on application code $(tasks.git-clone-ace-application.results.commit)"
            git push origin HEAD:main
        - name: USER_HOME
          value: /root
        - name: VERBOSE
          value: 'true'
      workspaces:
        - name: source
          workspace: ace-tekton-workspace
        - name: basic-auth
          workspace: github-pat
  workspaces:
    - name: ace-tekton-workspace
    - name: github-pat
